//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPipe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioPipe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Redirect is open source software provided under the MIT license..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Audio Redirect.
        /// </summary>
        public static string ContextMenuExitTitle {
            get {
                return ResourceManager.GetString("ContextMenuExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ContextMenuHelpTitle {
            get {
                return ResourceManager.GetString("ContextMenuHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ContextMenuSettingsTitle {
            get {
                return ResourceManager.GetString("ContextMenuSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default device.
        /// </summary>
        public static string DefaultDeviceText {
            get {
                return ResourceManager.GetString("DefaultDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My device isn&apos;t in the list!.
        /// </summary>
        public static string DeviceMissingCaption {
            get {
                return ResourceManager.GetString("DeviceMissingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it your default playback device? Audio Redirect can only redirect from your default device to a different one, so try changing your default playback device to something else first..
        /// </summary>
        public static string DeviceMissingText {
            get {
                return ResourceManager.GetString("DeviceMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My device still isn&apos;t in the list!.
        /// </summary>
        public static string DeviceStillMissingCaption {
            get {
                return ResourceManager.GetString("DeviceStillMissingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some devices support an alternate, low-latency driver mode that may not work with Audio Redirect. If your device has something like an ASIO or &quot;advanced driver&quot; mode, try turning it off..
        /// </summary>
        public static string DeviceStillMissingText {
            get {
                return ResourceManager.GetString("DeviceStillMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is busy. Is another program using it in exclusive mode?.
        /// </summary>
        public static string ErrorDeviceBusy {
            get {
                return ResourceManager.GetString("ErrorDeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Redirect.
        /// </summary>
        public static string ErrorTitleCannotCreatePipe {
            get {
                return ResourceManager.GetString("ErrorTitleCannotCreatePipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error. HRESULT: {0:X8}.
        /// </summary>
        public static string ErrorUnknownHresult {
            get {
                return ResourceManager.GetString("ErrorUnknownHresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size.
        /// </summary>
        public static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute source device when redirect is active.
        /// </summary>
        public static string MuteSourceWhenPipeIsActive {
            get {
                return ResourceManager.GetString("MuteSourceWhenPipeIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report any bugs you find on GitHub:.
        /// </summary>
        public static string PleaseReportBugs {
            get {
                return ResourceManager.GetString("PleaseReportBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Redirect.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        public static string Stability {
            get {
                return ResourceManager.GetString("Stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleOff {
            get {
                return ResourceManager.GetString("ToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleOn {
            get {
                return ResourceManager.GetString("ToggleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Redirect.
        /// </summary>
        public static string TrayIconText {
            get {
                return ResourceManager.GetString("TrayIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
